### ISSUE TITLE
invalid block when creating new repo

### ISSUE THREAD

**Issue by isaacJChen** [ipfs/js-ipfs-repo#226]
I am getting this error when creating a new repo.

`(node:1824) UnhandledPromiseRejectionWarning: Error: invalid block`

This is how I am constructing the repo I then pass it into IPFS-js then the error happens
`repo = new ipfsRepo('localIPFSDirectory');`

Upon further investigation. I noticed that `isBlock` method is looking for ipld block
![image](https://user-images.githubusercontent.com/26752423/79799882-139d1b00-8310-11ea-97b6-410f11aa84d5.png)
but my object is an ipfs block 
![image](https://user-images.githubusercontent.com/26752423/79799917-231c6400-8310-11ea-9c2f-185b4557270f.png)

I am not sure what the cause of the issue is, but it happens when I use ipfs-repo.

ipfs-repo version: "ipfs-repo": "2.0.0"
ipfs version: "ipfs": "0.42.0"

**Comment by achingbrain** [comment]
Please hold off on using `ipfs-repo@2.x.x` with `ipfs` until https://github.com/ipfs/js-ipfs/pull/2932 is merged & released.

The `ipfs-block` module was renamed `ipld-block` but because they export classes the modules are not compatible.  The PR above will bring `ipld-block` compatibility to `ipfs` and then you'll be able to upgrade to `ipfs-repo@2.x.x`.

**Comment by achingbrain** [comment]
I'm closing because all the relevant modules were released, please reopen if you are still seeing this problem.
